language: java

addons:
  sonarcloud:
    organization: "mavarazo"
    token:
      secure: "OJrw1BjoE2Ffpk3CPGiTSa89lUD8YbjOO0BffNNgTRUf7E7zeDlA6vgGc1f3ka+DJRKI2EQQ2hLQPDymGcklXudWVyQTZ6wN6aAdSWWNVPyToHGsnzlemdKZgr81WMmpudu/dH7Nb0eQMaoHn93HgXyMT5W0TzK1oy7GnZ63WXWuiLmLqM5mFF2lTcGw6uYBQufhy1nAuQP10bdXPng+R9t999IgWsO0jxJVXwqT3zxjDEG4+HGwLhsDgm5a5sa61GxTMVpji0IB1QLdIKyxxBBtoJO0gRfBrLrObspVZxFT6fVbkSMEwoWTjnLUnO6QUj16ZLM2TFfTI6ohjTeAV729pZL2zuaaimEDeYI/bgWCB8V37KezdFG0/MQbO9PbMcnjZIl3mqhVSt42dALdppt1a++Tax9qdud59RXDKB/+h7g30eBNsrys45G4zGvHFVRc4cQX+Uxf78vRmXhsAPFNvqUDZfkENZI5i4nnnUkvR7LseXVUoquFL4088MldmcnFETSwEbEdz9f1LvlIhTtoCp2QyQW3e4EpJ+YfrnoRldS9Glkb0D7VItRn6WNyVkVXy2l4kK8CgemdlLKNF02l6vGhfotvzbaEpqGlAfmJC1aGOrT4UuLZDigxYcd0aNe+MG1z/zQAERKsINoh9yB6BTAuxN+8KN4kxz5MLWA="

script:
  - ./gradlew sonarqube
