language: java

addons:
  sonarcloud:
    organization: "mavarazo"
    token:
      secure: "B6C/opmcNLnO+64aBsHC5Yf6Y2eoyIVuaTN/Wy7wG840OxsfCWZB9CBZV3yQxTO6tBMem+OIkZBOaVcSP5TqmxeEE9WKnmDwKckS5urrMXH5NRcIQ/5UBaUF2gu4bIaw8bFttEjm7DVELkUl8oXY+Vi559sWXFA33CSvUt7h2ZRIRLqRY64mU13zQH6O304UxIYhxJOSdeeGu3qqtY7ZyMcNse+SrdTa9ivWEewR/48waVrUnW7/p81wZE5i8z4ZxMcDsx0m37Wu3JSh269CJidgENPqfIxhrNK1f/EimAsIIf1iLtzNkPoEuwogTpbplyzEiuP0pb+vxCtvqTiFLbZ+LWY9knRxEncWUTmGCuofivGnk9CUBDG4UEOtpg3E5XefCqjP1VHARVwg7fbu9lG/XI3gQaDYmMoEy2jF5hxepMy33u5N3N6f4pUg5ZNku6SXRB1af/LTUiZWDNChFc7nSO9gv40O3sWry/pD7axdDVEJ/z2eU40HQcbSehsfvoUZiDfwDaXKBfkFiAbC9bqNiaRwhvLsXn4BoB73GBtPrjmu6EY133h9aV5k2i0QV9TsoW6ClaaoLjz52GISTZo4CnwSQpsvqVVtyAsD7TD2WkaI2Kkf7blhzjEIzbGuy+Q7U5DVJD3Ug/Acu1KuuKCL2OsDLHUpFvWQGC7Qk8g="

script:
  - ./gradlew sonarqube
