language: java

addons:
  sonarcloud:
    organization: "mavarazo"
    token:
      secure: "SM+WfRlL7pesKJf67+CPoG7I6vdHsamwjyXY2agXdw13/CUcap4acngUOzCAjAP8vFi418m9whPK52VEIJHfvdePhSLwzaU9R1d4XmGwWSfeTCB7rxXT33v+7/Pi3yorPOZxYcCK2d9DV1CxcWzl8WDMNRQyO9OgxMR3E1egFQ1frYMSGuxxxyhZv46FIIKrmyZu3nxRW4qLafAIu1e7FiRIM84nxrnBbcNkMiTXAk3WfuSVjz6z82mYWYy4bEG3qIQiKUtR2s0CLOhIUW5h3nezawFssAEEZdtNJdhU4tFZNB7Fn/L/hQ4CAig5/BH8yy+UrZk7lY77lzgp6e+qUtPJFmI6zZyRPQ9Hs7SK4gYgGFlXRb6vUlzhaOIozg0joHaTcPALTMuRpb6aOJgkZuxZMNF/pIQWJtxCdTMlRGr9lVsUL3Eecb1K6mnxkZmPGiaW34T0j3DAmHgNKf10VXQMz/O2gA4101JjAlDv42G3nK5Ze2psKZsD/W1pOokOcru2DAIqWa1BfgLpw5yYuBsvO00Zx0kmiWVsGkRGDcAI7vAd0dhWJmwDISO0cd6rxkfP+lBSj2o9qjtwQEfLZheWJS6S3ywsy6GZ2PnEs1N5kXe6meaZrvgGTetWjQx9NrMV1Q3aZQqnrDDDR2AzGuJqHD6cxYvZAGOWVl+WwDM="

script:
  - ./gradlew sonarqube
