mkm:
  accessTokenSecret: ${ACCESS_TOKEN_SECRET}
  accessTokenApp: ${ACCESS_TOKEN}
  appSecret: ${APP_SECRET}
  appToken: ${APP_TOKEN}
  apiVersion: 2.0
  apiUrl: https://api.cardmarket.com/ws/v

spring:
  application:
    name: Decksy
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/Downloads/decksy_database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: validate
